### PR TITLE
chore: bump tss-esapi crate to 7.4

### PR DESCRIPTION
**Pull request by nullr0ute**
There's a few minor fixes and no changes in API so let's bump to 7.4 for TPM2 support.

### CODE REVIEW

**Comment by 7flying** [comment]
I don't understand why this breaks the rust-aws-nitro-enclaves-cose too

**Comment by nullr0ute** [comment]
> I don't understand why this breaks the rust-aws-nitro-enclaves-cose too

I think the breakage is the known issue we already have with rust-aws-nitro-enclaves-cose where we patched it in Fedora.

**Comment by 7flying** [comment]
> > I don't understand why this breaks the rust-aws-nitro-enclaves-cose too
> 
> I think the breakage is the known issue we already have with rust-aws-nitro-enclaves-cose where we patched it in Fedora.

yes, but it wasn't showing up upstream before, I need to take a look to check how we can avoid this upstream too, otherwise our tests and builds are all broken

**Comment by nullr0ute** [comment]
> > > I don't understand why this breaks the rust-aws-nitro-enclaves-cose too
> > 
> > 
> > I think the breakage is the known issue we already have with rust-aws-nitro-enclaves-cose where we patched it in Fedora.
> 
> yes, but it wasn't showing up upstream before, I need to take a look to check how we can avoid this upstream too, otherwise our tests and builds are all broken

I think I can add a commit to this PR that will mitigate it

**Review by 7flying — APPROVED** [review]
Packit builds are failing but we'll be ignoring them for the time being

**Pull request merged**
