### PR TITLE
database enhancements

### PR DESCRIPTION
**Pull request by runcom**
[chore: store: db: reuse connection pool](https://github.com/fdo-rs/fido-device-onboard-rs/commit/68a7ac15131028f46089d5b67e5ec91ed1a34161)

The pool object is meant to be reused and since we're initializing the
store as part of a long running process, we should save the pool object
and pass it around/use it.

[chore: store: db: refactor database configuration](https://github.com/fdo-rs/fido-device-onboard-rs/commit/b61ec7e83291ee35db04e2ca846e6084130b0e3d)

This mainly comes from @mmartinv comment https://github.com/fdo-rs/fido-device-onboard-rs/pull/556/files#r1465996442

### CODE REVIEW

**Comment by nullr0ute** [comment]
Is this ready for review? Looking to be ongoing updates so maybe should be a draft until it's ready

**Review by 7flying — COMMENTED** [review]
You should move the removal of store/src/db.rs into the first commit since you are already creating two separate files for sqlite and postgres that have the pool reuse modification

**Comment by runcom** [comment]
> You should move the removal of store/src/db.rs into the first commit since you are already creating two separate files for sqlite and postgres that have the pool reuse modification

I figured it's probably better to have this enhancement as a single commit (too many moving pieces and I want to avoid to break bisect too)

**Comment by 7flying** [comment]
> > You should move the removal of store/src/db.rs into the first commit since you are already creating two separate files for sqlite and postgres that have the pool reuse modification
> 
> I figured it's probably better to have this enhancement as a single commit (too many moving pieces and I want to avoid to break bisect too)

That also works for me :+1:

**Review by 7flying — APPROVED** [review]
LGTM

**Pull request merged**
